### ISSUE TITLE
Add Git Authentication Support

### ISSUE THREAD

**Issue by marijenk** [pacphi/cf-butler#179]
Hi @pacphi,

Upon trying to integrate cf-butler using `git` set as the Policy Provider, it appears that there is not a way to pass Git credentials when deploying cf-butler to Pivotal Application Service.

I tried URL encoding my Git username/password and passing the credentials via the Git URI, but it fails with the following error:

```
2020-03-02T18:34:34.078-05:00 [APP/PROC/WEB/0] [OUT] [30m2020-03-02T23:34:34,073[m [33mWARN [m[[1;34mmain[m] [1;33mi.p.c.c.GitClient[m: Cannot clone Git repository at https://<username>:<password>@gituri.com/repo/repo-policies.git
2020-03-02T18:34:34.078-05:00 [APP/PROC/WEB/0] [OUT] org.eclipse.jgit.api.errors.TransportException: https://<username>:<password>@@gituri.com/repo/repo-policies.git: Authentication is required but no CredentialsProvider has been registered
```

Unfortunately, we won't be able to make this repository public, as it is internal.

Would it be possible to add functionality to support passing credentials in the same manner as the Git URI? I suspect it'd look something like this:

```
{
        "CF_POLICIES_PROVIDER": "git",
        "CF_POLICIES_URI": "https://mygit.uri.com",
        "CF_POLICIES_GIT_USERNAME": "username",
        "CF_POLICIES_GIT_PASSWORD": "password",
        "CF_POLICIES_FILE-PATHS": [
                "policy1-AP.json",
                "policy2-SP.json"
        ]
}
```

Let me know your thoughts

**Comment by pacphi** [comment]
This is certainly possible.  And pretty simple to do.  For optionality's sake we might also consider different modes of auth within [GitClient](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/client/GitClient.java).

This article provides some examples (hints) on how to go about it:

* http://www.lordofthejars.com/2016/09/authenticating-with-jgit.html

I'm open to PRs if you want to give this a try.  It may be a while before I have cycles to implement myself.

**Comment by pacphi** [comment]
Have a look at this [feature branch](https://github.com/pacphi/cf-butler/tree/add-git-auth-support).  Let me know if it satisfies your needs.  Note the updates in the configuration.  You no longer specify `CF_POLICIES_PROVIDER`.  All git-backed policies have configuration managed by property prefixed names like: `cf.policies.git`, `CF_POLICIES_GIT`.

**Comment by pacphi** [comment]
Completed as of https://github.com/pacphi/cf-butler/commit/7eac0ac0720ef96865a1d7abd2b9bf904c66086d

**Comment by marijenk** [comment]
I had started implementing it to see if I could get the code written, but you beat me to it :) 
I'll test it out with my team now and update you on our findings.

Thanks for your quick reply and efforts on implementing this feature! @pacphi

**Comment by marijenk** [comment]
Hi @pacphi ,

I tested out the changes and it seems to fail with the following error when I try to deploy to PAS:
```
Could not resolve placeholder 'vcap.services.cf-butler-secrets.credentials.CF_POLICIES_GIT_URI' in value "${vcap.services.cf-butler-secrets.credentials.CF_POLICIES_GIT_URI}"
```

I checked the `application-yml` file and I didn't see anything wrong with the references in your commit PR. I double-checked my secrets.json and validated that the syntax is correct using `jq`. Here's my example secrets.json:

```
{
        "TOKEN_PROVIDER": "userpass",
        "CF_API-HOST": "api.sys.domain",
        "CF_USERNAME": "cfusername",
        "CF_PASSWORD": "cfpassword",
        "CF_ORGANIZATION-BLACK-LIST": [
                "system"
        ],
        "CF_ACCOUNT-REGEX": "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",
        "CRON_COLLECTION": "* */4 * * * *",
        "CRON_EXECUTION": "* */5 * * * *",
        "CF_POLICIES_GIT_URI": "https://mygituri.com/repo/repo-policies.git",
        "CF_POLICIES_GIT_USERNAME": "myusername",
        "CF_POLICIES_GIT_PASSWORD": "mypassword",
        "CF_POLICIES_GIT_FILE-PATHS": [
                "policy1-AP.json"
        ],
        "EXPOSED_ACTUATOR_ENDPOINTS": "beans,env,info,health,metrics,scheduledtasks,loggers,mappings,prometheus"
}

```

Am I missing something?

**Comment by pacphi** [comment]
The above issue is fixed as of https://github.com/pacphi/cf-butler/commit/2c7b58fa164acd4a350665945919606a51611b90.  But we have another issue, that I'm tracking with #185.
