### ISSUE TITLE
Add cf-for-k8s support

### ISSUE THREAD

**Issue by pacphi** [pacphi/cf-butler#203]
Cloud Foundry for Kubernetes? Yup, see [cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s).

If we attempted to deploy cf-butler, we'd...

* need equivalent support for managing configuration (e.g., in ConfigMaps, Secrets)
* want to prune away unnecessary/unsupported dependencies (e.g., Credhub)
* need to refine, verify and/or disable functionality (e.g., OpsmanClient, ProductMetrics*)

The above is by no means an exhaustive list of concerns.  

What I'd like to do for MVP purposes is...

* Read and understand a collection of articles, tutorials, and documentation, like:
  * [Getting Started with Spring Boot on Kubernetes](https://www.katacoda.com/springguides/scenarios/getting-started)
  * [Guide to Spring Cloud Kubernetes](https://www.baeldung.com/spring-cloud-kubernetes)
  * [Spring Cloud Kubernetes](https://spring.io/projects/spring-cloud-kubernetes) support for...
    * PropertySources - [ConfigMaps](https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#configmap-propertysource), [Secrets](https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#secrets-propertysource)
    * [DiscoveryClient](https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#ribbon-discovery-in-kubernetes) and CircuitBreaker support (e.g., Hystrix v Resilience4J)
  * [kustomize sample for Spring Boot](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/springboot)
  * [Liveness and Readiness Probes with Spring Boot](https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot)
* Introduce and/or update necessary config, implementation, and documentation to support a stripped-down but functional deployment of cf-butler on cf-for-k8s
    * Documentation should explain in detail...
      * the steps to build, publish images to a private registry (e.g., Harbor)
      * how to define/assemble runtime configuration
    * First attempt will by no means result in feature parity
    * There will be gaps and/or broken/disabled functionality because of lack of support in [cf-java-client](https://github.com/cloudfoundry/cf-java-client) API
      * call these occurrences out in the documentation

Aspiring in a second pass to...
* Adhere to best practices around secure deployment (e.g., authenticating and authorizing requests - service accounts, RBAC, etc.)

With the above in mind, I might want to entertain re-organizing the structure of this repo to support e.g., common, cf-bosh and cf-for-k8s modules, resulting Impact:

* changes to travis-ci and github-workflow
* additional artifacts produced (library and deployables)

**Comment by dashaun** [comment]
Willing to work on this, but won't be able to start until next week.

**Comment by pacphi** [comment]
RIP Cloud Native Buildpacks.  Long live Packeto! https://packeto.io.

Learned a bit over the last 24h about the forthcoming release candidate of Spring Boot 2.3.0 and how it will update its base image to be 

```
bootBuildImage {
	builder = "gcr.io/paketo-buildpacks/builder:base-platform-api-0.3"
}
```

this instruction was added to `build.cnb.gradle` a variant of `build.gradle` with the Gradle Git plugin removed.

I also introduced a variant of the convenience script used to push the app with no-start option, create a cups service, bind it to the app, then start the app; see `scripts/deploy.k8s.sh`.

Lastly, I introduced `manifest.cf4k8s.yml`, a variant of `manifest.yml` that works with Packeto images that are deployed to a `cf-for-k8s` or `tas-for-k8s` target k8s cluster.

So how does this all come together?

Check out the [cf4k8s-support](https://github.com/pacphi/cf-butler/tree/cf4k8s-support) branch.

If you have Harbor integrated with `kpack` in your `cf-for-k8s` install as I do with https://github.com/niallthomson/tanzu-playground/blob/master/terraform/gke/cf-for-k8s/README.md, then you could get `cf-butler` built and deployed in the following manner:

```
git clone https://github.com/pacphi/cf-butler.git
git checkout cf4k8s-support
docker login -u admin https://{harbor-hostname}
docker tag cf-butler:0.1-SNAPSHOT {harbor-hostname}/library/cf-butler:0.1-SNAPSHOT
docker push {harbor-hostname}/library/cf-butler:0.1-SNAPSHOT
```
> Replace occurrences of `{harbor-hostname}` above with your Harbor instance's hostname

Make a directory called `config`.
Create a secrets file called `secrets.json` and save within the `config` directory.
It should contain something like the following

```
{    
    "PIVNET_API-TOKEN": "{your-pivnet-token}",
    "PIVNET_ENABLED": true,
    "CF_TOKEN-PROVIDER": "userpass",
    "CF_API-HOST": "{cf-api-endpoint}",
    "CF_USERNAME": "admin",
    "CF_PASSWORD": "{replace_me}",
    "CF_SKIP_SSL_VALIDATION": true,
    "CRON_COLLECTION": "0 0 0 * * *",
    "CRON_EXECUTION": "0 0 2 * * *",
    "CF_POLICIES_GIT_URI": "https://github.com/pacphi/cf-butler-sample-config.git",
    "CF_POLICIES_GIT_FILE-PATHS": [
        "delete-applications-policy-sample-AP.json",
        "delete-service-instances-policy-sample-SIP.json",
        "scale-applications-policy-sample-AP.json",
        "stop-applications-policy-sample-AP.json",
        "change-stack-applications-policy-sample-AP.json",
        "query-policy-h2-sample-QP.json",
        "endpoint-policy-sample-EP.json",
        "hygiene-policy-sample-HP.json"
    ],
    "EXPOSED_ACTUATOR_ENDPOINTS": "info,health,httptrace,metrics,scheduledtasks,loggers,prometheus",
    "NOTIFICATION_ENGINE": "none"
}
```

Then

```
cf push -f manifest.cf4k8s.yml -o {harbor-hostname}/library/cf-butler:0.1-SNAPSHOT --no-start
cf cups cf-butler-secrets -p config/secrets.json
cf bs cf-butler cf-butler-secrets
cf start cf-butler
```

If you have [httpie](https://httpie.org) installed, quickly checkout the result of 

```
http http://cf-butler.{cf-api-endpoint}/snapshot/detail
```

This will be made more convenient in a subsequent effort.

As mentioned previously there's still a lot left undone and/or broken.  Enjoy what's here now!

**Comment by pacphi** [comment]
As of today [Spring Boot 2.3.0.RC1 is available](https://spring.io/blog/2020/05/01/spring-boot-2-3-0-rc1-available-now).  That simplifies the steps above a bit. You can continue to use the above or if you just want to bring source to the party and watch cf-for-k8s take care to build, package, and run adapt your steps to be:

```
git pull
./scripts/destroy.sh
./scripts/deploy.k8s.sh _ config/secrets.json
```

> Assumes you tried out the prior set of steps and you are in the root of the cloned project directory.

Can't make it much easier than that to deploy.

**Comment by pacphi** [comment]
Closing this out. See 21b235fe840fd9e1ab9ac3534889b3233ee51c14 and 8d5d81eb8fa4233045001c383e732290558b51c0.
