### ISSUE TITLE
Service instance count for snapshot/summary gives different result when running at different times. 

### ISSUE THREAD

**Issue by deiveehan** [pacphi/cf-butler#217]
The service instance count in the snapshot/summary provides different results at different times. 

Example:
curl -s https://cf-butler-<domain.com>/snapshot/summary | jq

When running 1st time provides the below result. 
"service-instance-counts": {
    "by-organization": {
      “ORG-1”: 9,
      "ORG-2": 1,
      "ORG-3": 10,
      "ORG-4": 4,
      "ORG-5": 5,
      "ORG-6": 71,
      "ORG-7": 12,
      "ORG-8": 1,
      "ORG-9": 19
    },

When running second time, provides different values..

"service-instance-counts": {
    "by-organization": {
      "ORG-1": 2,
      "ORG-2": 20,
      "ORG-3": 10,
      "ORG-4": 57,
      "ORG-5": 5,
      "ORG-6": 266,
      "ORG-7": 8,
      "ORG-8": 1,
      "ORG-9": 58
    }

Using the below configurations.
{
    "CF_TOKEN-PROVIDER": "userpass",
    "CF_API-HOST": "my-domain-name",
    "CF_USERNAME": "admin",
    "CF_PASSWORD": "<i-wont-share-the-password-;-)>",
    "CF_ORGANIZATION-BLACK-LIST": [
         "a",
         "b",
         "c",
         "d",
         "e",
         "f"
     ],
    "CF_ACCOUNT-REGEX": "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",
    "CRON_COLLECTION": "* */10 * * * *",
    "CRON_EXECUTION": ""* */5 * * * *",
    "EXPOSED_ACTUATOR_ENDPOINTS": "beans,env,info,health,metrics,scheduledtasks,loggers,mappings,prometheus"
}

Did the basic setup required not sure if I need to do anything else apart from the above to get this working..

**Comment by pacphi** [comment]
Have you consulted the application logs to see if there were any issues on collection between runs?

**Comment by pacphi** [comment]
Since I have not heard from you https://github.com/deiveehan I'm going to close this issue. If you wish to provide more detail and re-open please feel free to do so.
