### ISSUE TITLE
Expand use beyond organization level

### ISSUE THREAD

**Issue by JuanFCabrera** [pacphi/cf-butler#358]
it is my understanding that currently cfbutler operates at an org level. is there any possibility to have it work at space level. our current desired use would be to exclude specific applications from cleanup. based on current documentation this does not seem possible.

**Comment by pacphi** [comment]
Whitelisting and blacklisting only apply to organizations. What is the use case? Do you want to report on or act on (a) specific application(s)?  If the former you might consider the use of a Query Policy.  If the latter (e.g., a delete policy), then we'd have to look at updating the logic in the [isBlackListed](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/DeleteAppPolicyExecutorTask.java#L185) and [isWhiteListed](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/DeleteAppPolicyExecutorTask.java#L189) methods.  `ApplicationPolicy` would need to hold some additional state, maybe a `Map<String, String>` named spacesWhiteList, where the key is the organization name and the value is the space name? I'm a little weary of going down this path without some more design thought (allowing for more flexible definitions of whitelists).

**Comment by JuanFCabrera** [comment]
Chris,

Our use case would be as follows,  set up a policy where it works through a delete policy for org A and E but skips spaces C and G. we have some application teams the startup certain applications  once or twice a week within those specific spaces to do data validation. The other spaces in the Org we would like the policy to run through.

Org A
                Space B
                Space C
                Space D

Org E
                Space F
                Space G

From: Chris Phillipson ***@***.***>
Sent: Monday, April 19, 2021 9:18 AM
To: pacphi/cf-butler ***@***.***>
Cc: Cabrera, Juan (Penske) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [pacphi/cf-butler] Expand use beyond organization level (#358)


This email originated from a Non-Penske sender. DO NOT OPEN attachments or links unless you recognize the sender and know that the content is safe.

Whitelisting and blacklisting only apply to organizations. What is the use case? Do you want to report on or act on (a) specific application(s)? If the former you might consider the use of a Query Policy. If the latter (e.g., a delete policy), then we'd have to look at updating the logic in the isBlackListed<https://urldefense.com/v3/__https:/github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/DeleteAppPolicyExecutorTask.java*L185__;Iw!!DRKjGdBm7_l7!VV4YqOCm6NXTosZEeKNjujsCmkQqyzUBUqsPJ3iUIGgmJbuDieFIlkjNrX384gZqsA$> and isWhiteListed<https://urldefense.com/v3/__https:/github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/DeleteAppPolicyExecutorTask.java*L189__;Iw!!DRKjGdBm7_l7!VV4YqOCm6NXTosZEeKNjujsCmkQqyzUBUqsPJ3iUIGgmJbuDieFIlkjNrX0Et02aRg$> methods. ApplicationPolicy would need to hold some additional state, maybe a Map<String, String> named spacesWhiteList, where the key is the organization name and the value is the space name? I'm a little weary of going down this path without some more design thought (allowing for more flexible definitions of whitelists).

**Comment by pacphi** [comment]
I suppose we need to satisfy both whitelist (includes) and blacklist (exclude) spaces. The latter seems like what you want, and wouldn't be too difficult to add.

Maybe the configuration could be adapted like so...

### Sample application.yml

```yaml
cf:
  spacesBlackList:
     - "Org-A:Space-A"
     - "Org-E:Space-A"
     - "Org-E:Space-B"
     - "Org-E:Space-C" 
     - "Org-E:Space-D" 
```

And then we'd add a `Set<String> spacesBlackList` to `PasSettings.java` and a companion accessor method.

And if the operator defined a spacesBlackList in addition to an orgBlackList it should take precedence over the orgBlackList for the same organization(s).

**Comment by pacphi** [comment]
The feature branch has been merged to the main line.
