### ISSUE TITLE
Cannot access Opsmanager with user/pwd when external identity provider via SAML or LDAP integration

### ISSUE THREAD

**Issue by erboucherie** [pacphi/cf-butler#380]
Hello , we would like to use the OPsmanager endpoints to get overview of all the product version installed , but we are facing an issue to connect the Opsmanager with user/pwd .
This is due to the integration of a Saml Identity provider (https://docs.pivotal.io/ops-manager/2-10/opsguide/config-rbac.html#enable-saml) .
With such integration , only client/secret can be used to authenticate .
Is it planned to add such a feature to cf-butler (in addition to user/pwd) ?
Thanks in advance
Eric

**Comment by pacphi** [comment]
Would need to provide an option to configure how the client authenticates.  Presently, [OpsmanAccessTokenProvider](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/client/OpsmanAccessTokenProvider.java) is implemented to support _password grant_.  To address your request we would need to implement [SAML2 Bearer Grant](https://docs.cloudfoundry.org/api/uaa/version/4.35.0/index.html#saml2-bearer-grant).

**Comment by pacphi** [comment]
- [ ]  Obtaining an **assertion** may be challenging to do consistently based on [IdP](https://www.pingidentity.com/en/resources/client-library/articles/saml.html).

**Comment by pacphi** [comment]
@erboucherie Please try out this [branch](https://github.com/pacphi/cf-butler/tree/issue-380) to see if it meets your needs.  Opted to add support for `client_credentials` token grant.

**Comment by erboucherie** [comment]
Hello @pacphi . I just tried it , and it works perfectly . The only comment i could have is that it would be nicer if we could set those new parameters via Environment variables (**om.grantType** , **om.clientSecret**) like we do for **om.enabled** for instance .
That will make the configuration easier than setting different application-{env}.yml file .
But anyway , it works .
Thanks a lot for your velocity .
Best regards
Eric

**Comment by pacphi** [comment]
This [PR](https://github.com/pacphi/cf-butler/pull/381) closes the issue.
