### ISSUE TITLE
SSO Authentication

### ISSUE THREAD

**Issue by lerytke** [pacphi/cf-butler#41]
At some point could you add SSO based authentication to the endpoint so the information is not exposed to the outside world

**Comment by pacphi** [comment]
Why not introduce an API Gateway? You might look at this sample project for inspiration. https://github.com/artemMartynenko/spring-cloud-gateway-oauth2-sso-sample-application

**Comment by dashaun** [comment]
I'm a USER, deploying to my own org.

I'm required to use SSO for login.

I can only use `TOKEN_PROVIDER="userpass"`

Is this possible?

**Comment by pacphi** [comment]
You can use `TOKEN_PROVIDER=sso`.  You must authenticate as the user before deployment.  Then use the refresh token in .cf/config.json.  See https://github.com/pacphi/cf-butler#with-sso-authorization.

**Comment by dashaun** [comment]
This is working as documented!  This can be closed.

**Comment by pacphi** [comment]
Thank you @dashaun!
