### ISSUE TITLE
Examples of policy document payloads

### ISSUE THREAD

**Issue by aegershman** [pacphi/cf-butler#6]
In order to better evaluate/consume cf-butler, consider including a few examples of policy payloads and a description of what they do.

## background

As the moment, it's hard for me to tell what the total set of policy configuration options are available. Perhaps I am looking in the wrong place, though-- I assume it's intended that they're deduced from the [application policy](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/domain/ApplicationPolicy.java) and [serviceinstancepolicy](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/domain/ServiceInstancePolicy.java) classes.

But even still, I'm unsure of what things like [`from-duration` vs. `from-datetime` entails.](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/domain/ServiceInstancePolicy.java#L27-L31) Is that the difference of "how old the instance has been around" vs. "is the instance older than <some-arbitrary-datetime>"? These kinds of explanations on the policies themselves would be helpful. (Again, maybe I'm totally looking in the wrong place though!)

**Comment by pacphi** [comment]
The README.md includes an example payload. And you can dive into the /tests folder for some other ideas. I could look into integrating a JSON Scema validator, but that feels a bit heavy.

**Comment by aegershman** [comment]
Sure thing. There are just some fields which aren't entirely clear to me, e.g., `from-duration` vs. `from-datetime`, could be entirely my hangup. Thanks for the response 👍
