### ISSUE TITLE
Add an endpoint that provides an at-a-glance view on installed product freshness

### ISSUE THREAD

**Issue by pacphi** [pacphi/cf-butler#62]
Cf-butler already provides endpoints for capturing product and release data from both the Pivotal Network and an Operations Manager. Why not combine this data into a useable report for operators?

Something like

from Operations Manager

* Product name
* Installed Product Release Version

from Pivotal Network

* Latest Product Release Version
* Latest Product Release Date
* (lookup) Installed Product Release Date

For each product calculate the # of days between the installed version and the latest available version.

This would provide operations teams an at-a-glance view of how fresh each installed product is.  It might help drive a service level objective on product freshness. E.g., the platform team will ensure through automation or other means that installed product versions available on each managed foundation is only ever N-2 versions behind.

**Comment by pacphi** [comment]
What is a product?  A tile, stemcell or buildpack.

**Comment by dashaun** [comment]
I think that is valuable for all 3.

**Comment by pacphi** [comment]
Let's not forget buildpacks, https://github.com/pacphi/cf-butler/commit/7f3a2b5f76cde01eb2e969a8dd2431b93a0c286b

**Comment by pacphi** [comment]
Going to leave this open for remarks.  I still think stemcells is an interesting case, but maybe not that high-value?

**Comment by aegershman** [comment]
I can attest the value of having stemcell-related statistics. When internal teams advocate for/have to continually prove the value of CF, they're asked to provide _some_ kind of quantifiable data on "number of operating system patches taken" and speed to which those patches were applied. This data is extremely helpful when CF is squaring up against  "traditional" deployment operations (code plopped directly onto VMs which are _sometimes_ patched?). This is the kind of data that's helpful for platform operators when justifying (P)CF to their boss' boss' boss and/or to be used in slide decks. It's actually very helpful. And often the next question is "okay but how many VMs did you repave?" These might seem like silly questions once the [corporate culture has higher standards](https://builttoadapt.io/the-three-r-s-of-enterprise-security-rotate-repave-and-repair-f64f6d6ba29d) and familiarity with BOSH/upgrades/etc., but until that point, having data which demonstrates number of stemcells ("os patches") and other similar data is so incredibly helpful when establishing a cultural foothold... Plus it's cool to track and to challenge yourself && other platform engineering teams into who can safely take stemcells / repave the fastest.

**Comment by pacphi** [comment]
Stemcell release metrics now reporting as of f2a8d05dcc8dd4dd3f572471a46e6d13f7e2ff15.
