### ISSUE TITLE
Does cf-butler want a persistent data service to store /reports?

### ISSUE THREAD

**Issue by aegershman** [pacphi/cf-butler#7]
In order to view logging on actions cf-butler took, `GET /reports` can be used. However it's unclear if there is an intent to use a persistent data service (mysql) to store those reports for longer than the life of the instance.

Disclaimer: I didn't look too deep in the source code for it, but figure it might be worth pointing out that it's something I looked for in the docs.

**Comment by pacphi** [comment]
Currently the internal data store is just an in-mem db. Since we’re using David Moten’s rxjava2-jdbc driver it’s perhaps just a matter of adding a Spring profile to application.yml and a supported DB driver to build.gradle, e.g. PostgreSQL.

**Comment by aegershman** [comment]
Gotcha, just clarifying. Thanks for the response 👌

**Comment by pacphi** [comment]
I'm going to work on this a bit and include an example of how to integrate an external Postgres database.

**Comment by pacphi** [comment]
Support for an external PostgreSQL database added in this commit 545fbe5b168e89d9fc1c2dd1ed170037896fc87e.
