### ISSUE TITLE
Ability to consume policy definitions directly from a git repository

### ISSUE THREAD

**Issue by aegershman** [pacphi/cf-butler#8]
(This is just an idea. I realize it's probably way more work / complexity than the value it might bring. Just puttin' it out there, though)

As a PCF operator who shares responsibilities with others, in order to change the set of policies used by cf-butler, I could see value in being able to store policies in plaintext within a git repo, and have cf-butler update the policies it uses directly from the repository.

This allows traceability (who set this policy and why?), makes it easier to submit changes (just set a PR and when it's merged to master it's slurped up by cf-butler) and version-controlling of the policies used.

**Comment by pacphi** [comment]
I like this idea. Perhaps integrate Spring Cloud Config Client, then each policy is just a .json file in the repo?

**Comment by pacphi** [comment]
Figured this out. Rudiments of solution are available here: 3c32fa6db23eed3b570b7b412e18e7b334b3f62a.  Need to document both in cf-butler and in sample config repo, here: https://github.com/pacphi/cf-butler-sample-config.

**Comment by pacphi** [comment]
Added some docs in this commit: 80d0a15caf8b881970dab83c889c608324e8519e.
